name: Deploy Docker Container and Front-end to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy project files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          source: "."  # копируем весь проект
          target: "/home/bestway-app"

      - name: Run docker-compose on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          script: |
            cd /home/bestway-app

            echo "📦 Создаём .env (для Docker)"
            cat <<EOF > .env
            PYTHONPATH=/app/src
            PYTHONUNBUFFERED=1
            CELERY_APP_NAME=bestway
            CELERY_BROKER_URL=redis://redis:6379/0
            CELERY_RESULT_BACKEND=redis://redis:6379/1

            REDIS__HOST=redis://redis:6379/2
            REDIS__PASSWORD=

            DB__NAME=${{ secrets.DB__NAME }}
            DB__USER=${{ secrets.DB__USER }}
            DB__PASSWORD=${{ secrets.DB__PASSWORD }}
            DB__HOST=db
            DB__PORT=5432
            DB__POOL_SIZE=2
            DB__MAX_OVERFLOW=4
            EOF

            echo "📦 Создаём .env.db (для Postgres)"
            cat <<EOF > .env.db
            POSTGRES_DB=${{ secrets.DB__NAME }}
            POSTGRES_USER=${{ secrets.DB__USER }}
            POSTGRES_PASSWORD=${{ secrets.DB__PASSWORD }}
            EOF

            echo "📦 Создаём .env.fastapi (для запуска FastAPI напрямую)"
            cat <<EOF > .env.fastapi
            APP__NAME=${{ secrets.APP__NAME }}
            APP__BASE_URL=${{ secrets.APP__BASE_URL }}
            APP__DEBUG=${{ secrets.APP__DEBUG }}

            DB__NAME=${{ secrets.DB__NAME }}
            DB__USER=${{ secrets.DB__USER }}
            DB__PASSWORD=${{ secrets.DB__PASSWORD }}
            DB__HOST=localhost
            DB__PORT=5432

            JWT__SECRET_KEY=${{ secrets.JWT__SECRET_KEY }}
            JWT__ALGORITHM=${{ secrets.JWT__ALGORITHM }}

            REDIS__HOST=redis://localhost:6379/2

            SMS__SERVICE_URL=${{ secrets.SMS__SERVICE_URL }}
            SMS__API_KEY=${{ secrets.SMS__API_KEY }}
            SMS__CACHE_TIMEOUT=300

            PUSHER__APP_ID=${{ secrets.PUSHER__APP_ID }}
            PUSHER__KEY=${{ secrets.PUSHER__KEY }}
            PUSHER__SECRET=${{ secrets.PUSHER__SECRET }}

            PROXY__HOST=${{ secrets.PROXY__HOST }}
            PROXY__HTTP_PORT=${{ secrets.PROXY__HTTP_PORT }}
            PROXY__SOCKS5_PORT=${{ secrets.PROXY__SOCKS5_PORT }}
            PROXY__USERNAME=${{ secrets.PROXY__USERNAME }}
            PROXY__PASSWORD=${{ secrets.PROXY__PASSWORD }}

            CHATGPT__API_KEY=${{ secrets.CHATGPT__API_KEY }}

            UVICORN_HOST=0.0.0.0
            UVICORN_PORT=8004
            UVICORN_WORKERS=4
            UVICORN_RELOAD=false
            UVICORN_TIMEOUT_KEEP_ALIVE=5
            EOF

            echo "🧹 Останавливаем старые контейнеры (если есть)..."
            docker compose down

            echo "🚀 Собираем и запускаем новые контейнеры..."
            docker compose up -d --build

            echo "🟢 Перезапускаем FastAPI сервер..."
            pkill -f "uvicorn src.main:app" || true
            nohup uvicorn src.main:app --host 0.0.0.0 --port 8004 --env-file .env.fastapi > uvicorn.log 2>&1 &

            echo "✅ Готово!"
